project:
  type: website

website:
  title: "test quarto"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Quarto_E3CI_warm_ott.ipynb
        text: "E3CI_Warm_Test_1"
      - about.qmd


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    notebook-view: false




execute:   
  echo: false
